<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [2]:
import numpy as np
import pandas as pd
import folium

*It is good practice to display the library version numbers for future reference:*

In [3]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)
print('Folium: ', folium.__version__)

Numpy:  1.20.3
Pandas:  1.3.4
Folium:  0.12.1.post1


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [4]:
# wrong:
bikes = pd.read_table('data/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('data/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('data/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [5]:
#ANSWER:
bikes = pd.read_table('data/bikeshare.csv', sep=',', header = 0, index_col='instant')
bikes

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
1        2011-01-01       1   0     1   0        0        6           0   
2        2011-01-01       1   0     1   1        0        6           0   
3        2011-01-01       1   0     1   2        0        6           0   
4        2011-01-01       1   0     1   3        0        6           0   
5        2011-01-01       1   0     1   4        0        6           0   
...             ...     ...  ..   ...  ..      ...      ...         ...   
17375    2012-12-31       1   1    12  19        0        1           1   
17376    2012-12-31       1   1    12  20        0        1           1   
17377    2012-12-31       1   1    12  21        0        1           1   
17378    2012-12-31       1   1    12  22        0        1           1   
17379    2012-12-31       1   1    12  23        0        1           1   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
1                 1  0.24  0.2879  0.81     0.0000       3          13   16  
2                 1  0.22  0.2727  0.80     0.0000       8          32   40  
3                 1  0.22  0.2727  0.80     0.0000       5          27   32  
4                 1  0.24  0.2879  0.75     0.0000       3          10   13  
5                 1  0.24  0.2879  0.75     0.0000       0           1    1  
...             ...   ...     ...   ...        ...     ...         ...  ...  
17375             2  0.26  0.2576  0.60     0.1642      11         108  119  
17376             2  0.26  0.2576  0.60     0.1642       8          81   89  
17377             1  0.26  0.2576  0.60     0.1642       7          83   90  
17378             1  0.26  0.2727  0.56     0.1343      13          48   61  
17379             1  0.26  0.2727  0.65     0.1343      12          37   49  

[17379 rows x 16 columns]

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [6]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [7]:
df = pd.read_excel('data/Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [8]:
#ANSWER
df = pd.read_excel('data/Iris.xls', sheet_name = 'Data', usecols=[0,1,2,3,4])
df.head()

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0           1          0.2           1.4          3.5           5.1
1           1          0.2           1.4          3.0           4.9
2           1          0.2           1.3          3.2           4.7
3           1          0.2           1.5          3.1           4.6
4           1          0.2           1.4          3.6           5.0

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [9]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.csv')
df.head()

time  latitude  longitude  depth  mag magType  nst  \
0  2022-01-13T06:49:11.922Z   58.3053  -153.6169  61.30  2.5      ml  NaN   
1  2022-01-13T06:28:54.767Z   13.4101   -91.2384  35.00  4.1      mb  NaN   
2  2022-01-13T06:26:16.835Z   31.0209   131.4771  41.03  4.7      mb  NaN   
3  2022-01-13T05:47:11.142Z   51.2353  -179.2010  35.00  5.0      mb  NaN   
4  2022-01-13T04:13:45.942Z  -23.0109   -69.2739  77.48  4.1      mb  NaN   

     gap   dmin   rms  ...                   updated  \
0    NaN    NaN  0.54  ...  2022-01-13T07:28:29.040Z   
1  153.0  1.499  0.74  ...  2022-01-13T07:03:15.040Z   
2  127.0  1.003  0.66  ...  2022-01-13T06:47:23.040Z   
3  140.0  0.634  0.82  ...  2022-01-13T06:47:20.817Z   
4   68.0  0.267  0.66  ...  2022-01-13T04:28:18.040Z   

                                    place        type horizontalError  \
0            49 km WNW of Aleneva, Alaska  earthquake             NaN   
1  72 km SW of Puerto San José, Guatemala  earthquake             7.8   
2         55 km NE of Nishinoomote, Japan  earthquake             6.8   
3              191 km WSW of Adak, Alaska  earthquake             4.1   
4              71 km SSW of Calama, Chile  earthquake             4.7   

  depthError  magError  magNst     status  locationSource magSource  
0        1.0       NaN     NaN  automatic              ak        ak  
1        2.0     0.076    47.0   reviewed              us        us  
2        7.8     0.081    47.0   reviewed              us        us  
3        2.0     0.027   422.0   reviewed              us        us  
4        3.7     0.145    13.0   reviewed              us        us  

[5 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [10]:
# Workaround to convert unworkable https to http
# Import required libraries
from urllib import request
import ssl

# Convert data by changing the SSL context to unverified
url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"
context = ssl._create_unverified_context()
response = request.urlopen(url, context=context)
html = response.read()

# read converted html data to dataframe
df = pd.read_html(html)
df

[                         Bank NameBank           CityCity StateSt  CertCert  \
 0                    Almena State Bank             Almena      KS     15426   
 1           First City Bank of Florida  Fort Walton Beach      FL     16748   
 2                 The First State Bank      Barboursville      WV     14361   
 3                   Ericson State Bank            Ericson      NE     18265   
 4     City National Bank of New Jersey             Newark      NJ     21111   
 ..                                 ...                ...     ...       ...   
 558                 Superior Bank, FSB           Hinsdale      IL     32646   
 559                Malta National Bank              Malta      OH      6629   
 560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
 561  National State Bank of Metropolis         Metropolis      IL      3815   
 562                   Bank of Honolulu           Honolulu      HI     21029   
 
                  Acquiring Institutio

In [11]:
len(df)

1

In [12]:
df[0]

Bank NameBank           CityCity StateSt  CertCert  \
0                    Almena State Bank             Almena      KS     15426   
1           First City Bank of Florida  Fort Walton Beach      FL     16748   
2                 The First State Bank      Barboursville      WV     14361   
3                   Ericson State Bank            Ericson      NE     18265   
4     City National Bank of New Jersey             Newark      NJ     21111   
..                                 ...                ...     ...       ...   
558                 Superior Bank, FSB           Hinsdale      IL     32646   
559                Malta National Bank              Malta      OH      6629   
560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
561  National State Bank of Metropolis         Metropolis      IL      3815   
562                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                            Equity Bank    October 23, 2020     10538  
1              United Fidelity Bank, fsb    October 16, 2020     10537  
2                         MVB Bank, Inc.       April 3, 2020     10536  
3             Farmers and Merchants Bank   February 14, 2020     10535  
4                        Industrial Bank    November 1, 2019     10534  
..                                   ...                 ...       ...  
558                Superior Federal, FSB       July 27, 2001      6004  
559                    North Valley Bank         May 3, 2001      4648  
560  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
561              Banterra Bank of Marion   December 14, 2000      4646  
562                   Bank of the Orient    October 13, 2000      4645  

[563 rows x 7 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [13]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'column')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [14]:
#ANSWER
# Use .shape property of dataframe to generate row and column info
shape = bikes.shape

# Print answer
print("The bikes dataframe has %i rows and %i columns" % shape)

The bikes dataframe has 17379 rows and 16 columns


What are the column names in `bikes`?

In [15]:
#ANSWER
# Generate column name list with .columns function
cols = list(bikes.columns)

# Print answer
print("The column names of bikes are as follows:",*cols, sep = "\n")

The column names of bikes are as follows:
dteday
season
yr
mnth
hr
holiday
weekday
workingday
weathersit
temp
atemp
hum
windspeed
casual
registered
cnt


What are the data types of these columns?

In [16]:
#ANSWER
# Print text prior to answer
print('The data types of the columns are contained in the following table:')
# Use .dtypes function for the answer
bikes.dtypes

The data types of the columns are contained in the following table:


dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [17]:
#ANSWER
# Set index name as original column name
df.index.name = 'instant'
# Print answer
print('The index is', df.index.name)

The index is instant


https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [18]:
#ANSWER
print(bikes['season'])
print(type(bikes['season']))
print(bikes[['season']])
print(type(bikes[['season']]))
# answer below demonstrates that both pull the same data, but puts it in different containers

instant
1        1
2        1
3        1
4        1
5        1
        ..
17375    1
17376    1
17377    1
17378    1
17379    1
Name: season, Length: 17379, dtype: int64
<class 'pandas.core.series.Series'>
         season
instant        
1             1
2             1
3             1
4             1
5             1
...         ...
17375         1
17376         1
17377         1
17378         1
17379         1

[17379 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>


How would we use object notation to show the first 4 rows of `atemp`?

In [19]:
#ANSWER
bikes['atemp'][0:4]

instant
1    0.2879
2    0.2727
3    0.2727
4    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [20]:
#bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [21]:
#ANSWER
bikes.iloc[0]

dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed            0.0
casual                 3
registered            13
cnt                   16
Name: 1, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [22]:
#ANSWER
bikes.iloc[1]

dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     1
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.22
atemp             0.2727
hum                  0.8
windspeed            0.0
casual                 8
registered            32
cnt                   40
Name: 2, dtype: object

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER: The isnull function generates a dataframe where each value has been replaced by a boolean that returns 'True' if the value was the 'None' datatype, and 'False' if otherwise.

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [23]:
bikes.isnull().head()

dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
instant                                                                      
1         False   False  False  False  False    False    False       False   
2         False   False  False  False  False    False    False       False   
3         False   False  False  False  False    False    False       False   
4         False   False  False  False  False    False    False       False   
5         False   False  False  False  False    False    False       False   

         weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
instant                                                                         
1             False  False  False  False      False   False       False  False  
2             False  False  False  False      False   False       False  False  
3             False  False  False  False      False   False       False  False  
4             False  False  False  False      False   False       False  False  
5             False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [24]:
#ANSWER
bikes.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [25]:
#ANSWER
bikes.isnull().any()

dteday        False
season        False
yr            False
mnth          False
hr            False
holiday       False
weekday       False
workingday    False
weathersit    False
temp          False
atemp         False
hum           False
windspeed     False
casual        False
registered    False
cnt           False
dtype: bool

What is the Numpy object `nan` used for? (Write a descriptive answer.)

ANSWER: The Numpy object nan represents data entries that are undefined. In a pandas dataframe, it is use to represent missing values in the dataframe

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [26]:
#ANSWER
# Write division function
def div(a,b):
    # Use try/except to handle exceptions
    try:
        # Perform simple division
        c = a / b
    except ZeroDivisionError:
        # Return nan when errors occur
        c = np.nan
    # Return final value    
    return c

# Try regular division
print(div(6,4))
# Try divide by zero
print(div(6,0))

1.5
nan


Apply the Pandas `isna` function to the following data objects:

In [27]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [28]:
#ANSWER
print(pd.isna(x))
print(pd.isna(y))

False
True


In [29]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [30]:
#ANSWER
print(pd.isna(array))

[[False  True False]
 [False False  True]]


How is the pandas I/O parameter `na_values` used?

? ANSWER: na_values is used within a pandas read function (eg. read_csv()) to specify values that are to be changed to nan on generation of the dataframe.

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [31]:
#ANSWER
seasons = bikes['season'].nunique()
# Print result
print('There are %i seasons in the bikes dataframe' % seasons)

There are 4 seasons in the bikes dataframe


### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [32]:
#ANSWER
# Create function for answer
def range(dfwithcol):
    max = dfwithcol.max()
    min = dfwithcol.min()
    return print("The range of {0} is from {1} to {2}".format(dfwithcol.name, min, max))

# Use function for each column
range(bikes.index)
range(bikes['dteday'])
range(bikes['windspeed'])


The range of instant is from 1 to 17379
The range of dteday is from 2011-01-01 to 2012-12-31
The range of windspeed is from 0.0 to 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [33]:
# Select only columns with numerical data
bikes_float = bikes.select_dtypes(np.number)
# Use bikes_float min and maxes to generate values
bikes_min, bikes_max = (min(bikes_float.min()), max(bikes_float.max()))
# Print answer
print("The global minimum numerical value in the bikes dataframe is {0} and the global maximum is {1}".format(bikes_min, bikes_max))

The global minimum numerical value in the bikes dataframe is 0.0 and the global maximum is 977.0


### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [34]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [35]:
#ANSWER
bikes['atemp'].quantile((0.1, 0.25, 0.5, 0.75, 0.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [36]:
type(bikes['atemp'])

pandas.core.series.Series

In [37]:
bikes.sample(5)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
9383     2012-01-31       1   1     1  20        0        2           1   
5587     2011-08-25       3   0     8  16        0        4           1   
11320    2012-04-21       2   1     4  20        0        6           0   
3063     2011-05-12       2   0     5  12        0        4           1   
9604     2012-02-10       1   1     2   2        0        5           1   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
9383              1  0.40  0.4091  0.58     0.1045      15         223  238  
5587              1  0.72  0.7121  0.84     0.0000      16         105  121  
11320             3  0.50  0.4848  0.82     0.2985       5          34   39  
3063              1  0.58  0.5455  0.60     0.2239      43         164  207  
9604              1  0.26  0.2879  0.52     0.0896       7           9   16

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [38]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [39]:
#ANSWER
# atemp_level is a series of datapoints that matches the row index in the original dataframe to an assigned category based on the calculated bin ranges

Here is a random sample of `atemp_level`:

In [40]:
atemp_level.sample(5)          

instant
51       (-0.001, 0.25]
9893        (0.25, 0.5]
5572        (0.5, 0.75]
15738       (0.25, 0.5]
2366        (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64, right]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [41]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

instant
8042     mild
14379    warm
2004     cool
3236     warm
2670     warm
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [68]:
#ANSWER
# Incorporate atemp_level
bikes['atemp_level'] = atemp_level

# Generate dataframe corresponding to requirements
mild_season2 = bikes.loc[(bikes['season'] == 2) & (bikes['atemp_level'] == 'mild')]

# Count values
mild_values = len(mild_season2)

# Print answer
print('There are {0} values in bikes with a mild temperature in Season 2'.format(mild_values))


There are 1829 values in bikes with a mild temperature in Season 2


*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [43]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

print(a, '\n', a.shape, '\n\n')
print(b, '\n', b.shape, '\n\n')
print(c, '\n', c.shape, '\n\n')
print(d, '\n', d.shape, '\n\n')
print(e, '\n', e.shape, '\n\n')

[0. 0. 0.] 
 (3,) 


[[1. 1. 1.]] 
 (1, 3) 


[[[6 2 5 9]
  [6 6 1 1]
  [1 2 6 1]]

 [[2 6 7 6]
  [8 6 8 9]
  [3 3 4 9]]] 
 (2, 3, 4) 


[0 1 2 3] 
 (4,) 


[[1 2 3 4]
 [5 6 7 8]] 
 (2, 4) 




In [44]:
# Cleaning Data

## Load Data

Load rock.csv and clean the dataset.

In [45]:
# Use read_csv to load dataset into pandas dataframe
# Set header row as first row (0)
rockdf = pd.read_csv('data/rock.csv', header=0)

rockdf.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [46]:
# Print list of column names
print(list(rockdf.columns))

['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?', 'Year?', 'PlayCount', 'F*G']


In [47]:
# From above list, need to:
# Change columns names, consistent capitalisation
rockdf = rockdf.rename(columns={"Song Clean":"Song", "COMBINED":"Combined", "ARTIST CLEAN":"Artist", "First?":"First", "Year?":"Year"})

# Remove unneeded columns
rockdf = rockdf.drop(["First", "Year", "Combined", "F*G"], axis=1)

rockdf.head()

Song       Artist Release Year  PlayCount
0        Caught Up in You  .38 Special         1982         82
1            Fantasy Girl  .38 Special          NaN          3
2         Hold On Loosely  .38 Special         1981         85
3  Rockin' Into the Night  .38 Special         1980         18
4       Art For Arts Sake         10cc         1975          1

## Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [48]:
#Summarise all null data in column
print(rockdf.isnull().sum())

Song              0
Artist            0
Release Year    577
PlayCount         0
dtype: int64


In [49]:
# Replace null values in 'Release Year' column with 0
rockdf = rockdf.fillna(0)

# Verify result
print(rockdf.isnull().sum())

Song            0
Artist          0
Release Year    0
PlayCount       0
dtype: int64


## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [50]:
# Check column datatypes
print(rockdf.dtypes)


Song            object
Artist          object
Release Year    object
PlayCount        int64
dtype: object


In [51]:
# From above, is clear that 'Release Year' would be more useful as integers
# As there are
rockdf['Release Year'] = rockdf['Release Year'].astype(np.int64, errors='ignore')

# Verify
print(rockdf.dtypes)

Song            object
Artist          object
Release Year    object
PlayCount        int64
dtype: object


In [52]:
# Clearly, there is data in the column that cannot be converted to an integer.
# Create copy of column under different name
ReleaseCol = rockdf['Release Year'].copy()

# Change incorrect data to 0s with for loop
for i in ReleaseCol:
    # Try to satisfy conditional
    try:
        np.int64(i)
    # If conditional fails, convert value to 0
    except ValueError:
       index = [ReleaseCol.loc[ReleaseCol == i].index[0]][0]
       ReleaseCol[index] = 0

rockdf['Release Year'] = ReleaseCol


In [53]:
# Retry conversion
rockdf['Release Year'] = rockdf['Release Year'].astype(np.int64)

# Verify
print(rockdf.dtypes)

Song            object
Artist          object
Release Year     int64
PlayCount        int64
dtype: object


## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [54]:
# Run min and max functions
print(rockdf.min(), '\n')
print(rockdf.max())

# No unusual values, the zeroes in release year are intentional.


Song               #9 Dream
Artist          .38 Special
Release Year              0
PlayCount                 0
dtype: object 

Song            Ziggy Stardust
Artist                    a-ha
Release Year              2014
PlayCount                  142
dtype: object


## Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [55]:
# Create function with dataframe and row index as inputs
def songdesc(dataframe, rowindex):
    # Define relevant values
    song = dataframe['Song'][rowindex]
    artist = dataframe['Artist'][rowindex]
    bool1970 = dataframe['Release Year'][rowindex]

    # Create 1970 output expression
    output1 = 'before 1970' if bool1970 < 1970 else 'after 1970'

    # Final output
    return print('The song {0} by {1} was released {2}'.format(song, artist, output1))

# Example
songdesc(rockdf, 1312)



The song Comfortably Numb by Pink Floyd was released after 1970


## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [56]:
list(rockdf.columns)

['Song', 'Artist', 'Release Year', 'PlayCount']

In [74]:
# Create function with inputs
def floatconvert(dataframe):
    # Pull out column names and row numbers into lists
    columnnames = list(dataframe.columns)
    indexnum = list(dataframe.index)

    # Initialise empty dataframe with index and column names
    df = pd.DataFrame([], index=indexnum, columns=columnnames)

    # Try datatype conversion
    # Create for loop for columns
    for i in columnnames:
        # Nest for loop for rows
        for j in indexnum:
            # Use try/except block to handle values that cannot convert to float
            try:
                df[i][j] = np.float64(dataframe[i][j])
            except:
                df[i][j] = np.nan
    
    # To ensure, change each column to float type
    for i in columnnames:
        df[i] = df[i].astype(np.float64, errors='ignore')
    # Return the whole dataframe
    return df


# OTHERWISE column-by-column function:
def convert_to_float(column):
    column = pd.to_numeric(column, errors='coerce')
    
    return column



## Apply these functions to your dataset

In [75]:
# Apply first to rockdf, producing a new dataframe
rockdf_float = floatconvert(rockdf)

# Verify
print(rockdf_float.dtypes)
rockdf_float.head()

Song            float64
Artist          float64
Release Year    float64
PlayCount       float64
dtype: object


Song  Artist  Release Year  PlayCount
0   NaN     NaN        1982.0       82.0
1   NaN     NaN           0.0        3.0
2   NaN     NaN        1981.0       85.0
3   NaN     NaN        1980.0       18.0
4   NaN     NaN        1975.0        1.0

In [76]:
# Apply second to rockdf with .apply() method
rockdf.apply(convert_to_float)

# Verify
print(rockdf_float.dtypes)
rockdf_float.head()

Song            float64
Artist          float64
Release Year    float64
PlayCount       float64
dtype: object


Song  Artist  Release Year  PlayCount
0   NaN     NaN        1982.0       82.0
1   NaN     NaN           0.0        3.0
2   NaN     NaN        1981.0       85.0
3   NaN     NaN        1980.0       18.0
4   NaN     NaN        1975.0        1.0

## Describe the new float-only DataFrame.

In [77]:
# Use describe function
rockdf_float.describe()

Song  Artist  Release Year    PlayCount
count     2.000000     0.0   2230.000000  2230.000000
mean   1012.000000     NaN   1465.331390    16.872646
std    1367.544515     NaN    867.196161    25.302972
min      45.000000     NaN      0.000000     0.000000
25%     528.500000     NaN      0.000000     1.000000
50%    1012.000000     NaN   1973.000000     4.000000
75%    1495.500000     NaN   1981.000000    21.000000
max    1979.000000     NaN   2014.000000   142.000000

>




---



---



> > > > > > > > > © 2021 Institute of Data


---



---



